export const timezones = [
    { value: 720, name: '(UTC-12:00) Dateline Standard Time' },
    { value: 660, name: '(UTC-11:00) Niue Time, Samoa Standard Time' },
    { value: 600, name: '(UTC-10:00) Cook Is. Time, Hawaii Standard Time, Tahiti Time' },
    { value: 570, name: '(UTC-09:30) Marquesas Time' },
    { value: 540, name: '(UTC-09:00) Gambier Time, Hawaii Daylight Time' },
    { value: 480, name: '(UTC-08:00) Alaska Daylight Time, Pacific Standard Time, Pitcairn Standard Time' },
    { value: 420, name: '(UTC-07:00) Mountain Standard Time, Pacific Daylight Time' },
    { value: 360, name: '(UTC-06:00) Central Standard Time, Galapagos Time, Mountain Daylight Time' },
    { value: 300, name: '(UTC-05:00) Acre Time, Central Daylight Time, Colombia Time, Easter Is. Time, Eastern Standard Time, Ecuador Time, Peru Time' },
    { value: 270, name: '(UTC-04:30) Venezuela Time' },
    {
        value: 240,
        name: '(UTC-04:00) Amazon Time, Atlantic Standard Time, Bolivia Time, Cuba Daylight Time, Eastern Daylight Time, Guyana Time, Paraguay Time',
    },
    {
        value: 180,
        name: '(UTC-03:00) Argentine Time, Atlantic Daylight Time, Brasilia Time, Chile Time, Falkland Is. Time, French Guiana Time, Rothera Time, Suriname Time, Uruguay Time',
    },
    { value: 150, name: '(UTC-02:30) Newfoundland Daylight Time' },
    {
        value: 120,
        name: '(UTC-02:00) Fernando de Noronha Time, Pierre & Miquelon Daylight Time, South Georgia Standard Time, Western Greenland Summer Time',
    },
    { value: 60, name: '(UTC-01:00) Cape Verde Time' },
    { value: 0, name: '(UTC) Azores Summer Time, Coordinated Universal Time, Eastern Greenland Summer Time, Ghana Mean Time, Greenwich Mean Time' },
    { value: -60, name: '(UTC+01:00) British Summer Time, Central European Time, Irish Summer Time, Western African Time, Western European Summer Time' },
    {
        value: -120,
        name: '(UTC+02:00) Central African Time, Central European Summer Time, Eastern European Time, Middle Europe Summer Time, South Africa Standard Time',
    },
    {
        value: -180,
        name: '(UTC+03:00) Arabia Standard Time, Eastern African Time, Eastern European Summer Time, Israel Daylight Time, Moscow Standard Time, Syowa Time',
    },
    { value: -240, name: '(UTC+04:00) Armenia Time, Georgia Time, Gulf Standard Time, Mauritius Time, Reunion Time, Samara Time, Seychelles Time' },
    { value: -270, name: '(UTC+04:30) Afghanistan Time, Iran Daylight Time' },
    {
        value: -300,
        name: '(UTC+05:00) Aqtau Time, Aqtobe Time, Azerbaijan Summer Time, French Southern & Antarctic Lands Time, Maldives Time, Mawson Time, Oral Time, Pakistan Time, Tajikistan Time, Turkmenistan Time, Uzbekistan Time, Yekaterinburg Time',
    },
    { value: -330, name: '(UTC+05:30) India Standard Time' },
    { value: -345, name: '(UTC+05:45) Nepal Time' },
    {
        value: -360,
        name: '(UTC+06:00) Alma-Ata Time, Bangladesh Time, Bhutan Time, Indian Ocean Territory Time, Kirgizstan Time, Novosibirsk Time, Omsk Time, Qyzylorda Time, Vostok Time, Xinjiang Standard Time',
    },
    { value: -390, name: '(UTC+06:30) Cocos Islands Time, Myanmar Time' },
    { value: -420, name: '(UTC+07:00) Christmas Island Time, Davis Time, Indochina Time, Krasnoyarsk Time, West Indonesia Time' },
    {
        value: -480,
        name: '(UTC+08:00) Australian Western Standard Time, Brunei Time, Central Indonesia Time, China Standard Time, Hong Kong Time, Hovd Summer Time, Irkutsk Time, Malaysia Time, Philippines Time, Singapore Time',
    },
    { value: -525, name: '(UTC+08:45) Australian Central Western Standard Time' },
    {
        value: -540,
        name: '(UTC+09:00) Choibalsan Summer Time, East Indonesia Time, Japan Standard Time, Khandyga Time, Korea Standard Time, Palau Time, Timor-Leste Time, Ulaanbaatar Summer Time, Yakutsk Time',
    },
    {
        value: -570,
        name: '(UTC+09:30) Australian Central Standard Time (Northern Territory), Australian Central Standard Time (South Australia), Australian Central Standard Time (South Australia/New South Wales)',
    },
    {
        value: -600,
        name: "(UTC+10:00) Australian Eastern Standard Time (New South Wales), Australian Eastern Standard Time (Queensland), Australian Eastern Standard Time (Tasmania), Australian Eastern Standard Time (Victoria), Chamorro Standard Time, Chuuk Time, Dumont-d'Urville Time, Magadan Time, Papua New Guinea Time, Sakhalin Time, Ust-Nera Time, Vladivostok Time",
    },
    { value: -630, name: '(UTC+10:30) Lord Howe Standard Time' },
    {
        value: -660,
        name: '(UTC+11:00) Bougainville Standard Time, Kosrae Time, Macquarie Island Standard Time, New Caledonia Time, Pohnpei Time, Solomon Is. Time, Srednekolymsk Time, Vanuatu Time',
    },
    { value: -690, name: '(UTC+11:30) Norfolk Time' },
    {
        value: -720,
        name: '(UTC+12:00) Anadyr Time, Fiji Time, Gilbert Is. Time, Marshall Islands Time, Nauru Time, New Zealand Standard Time, Petropavlovsk-Kamchatski Time, Tuvalu Time, Wake Time, Wallis & Futuna Time',
    },
    { value: -765, name: '(UTC+12:45) Chatham Standard Time' },
    { value: -780, name: '(UTC+13:00) Phoenix Is. Time, Tokelau Time, Tonga Time, West Samoa Standard Time' },
    { value: -840, name: '(UTC+14:00) Line Is. Time' },
];
