name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install deps
        run: yarn install
      - name: npm package build
        run: yarn workspace @kanaries/graphic-walker build
      - name: Observable Plot renderer plugin build
        run: yarn workspace @kanaries/graphic-walker-renderer-observable-plot build
      - name: ECharts renderer plugin build
        run: yarn workspace @kanaries/graphic-walker-renderer-echarts build
      - name: Web app (playground) build
        run: yarn workspace playground build
      - name: Publish package
        run: npm publish --tag ${{ github.event.release.prerelease && 'pre' || 'latest' }}
        working-directory: ./packages/graphic-walker
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish observable plugin
        run: npm publish --tag ${{ github.event.release.prerelease && 'pre' || 'latest' }}
        working-directory: ./packages/renderer-observable-plot
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish echarts plugin
        run: npm publish --tag ${{ github.event.release.prerelease && 'pre' || 'latest' }}
        working-directory: ./packages/renderer-echarts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
